# https://juejin.cn/post/6844903967177064461#heading-6
builders:
  #  languageBuilder:
  #    import: "package:flutter_router_demo/language/builder.dart"
  #    builder_factories: [ "languageD2DBuilder" ]
  #    build_extensions: { ".dart": [ ".g.part" ] }
  #    build_to: source
  #  auto_apply: root_package
  #    defaults:
  #      generate_for:
  #        - lib/language/**
  #    applies_builders: [ "source_gen|combining_builder" ]

  # 如何自定义参数？
  # 如何自定义参数？
  # 如何自定义参数？
  languageBuilder:
    import: "package:flutter_router_demo/language/builder.dart"
    builder_factories: [ "json2DartBuilder" ]
    build_extensions: { ".json": [ ".g.dart" ] }
    build_to: source
    auto_apply: root_package
    defaults:
      generate_for:
        - assets/language/default.json

targets:
  $default:
    sources:
      # Need to replicate the default whitelist here or other build will break:
      - $package$
      - "benchmark/**"
      - "bin/**"
      - "example/**"
      - "lib/**"
      - "test/**"
      - "tool/**"
      - "web/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      # Project: custom src direction
      - "assets/language/**"