# https://juejin.cn/post/6844903967177064461#heading-6
builders:
  #  languageBuilder:
  #    import: "package:flutter_router_demo/language/builder.dart"
  #    builder_factories: [ "languageD2DBuilder" ]
  #    build_extensions: { ".dart": [ ".g.part" ] }
  #    build_to: source
  #  auto_apply: root_package
  #    defaults:
  #      generate_for:
  #        - lib/language/**
  #    applies_builders: [ "source_gen|combining_builder" ]

  #TODO: 如何自定义参数？Option.config!
  languageKeyBuilder:
    import: "package:flutter_router_demo/language/builder.dart"
    builder_factories: [ "languageKeyBuilder" ]
    build_extensions: { ".key": [ ".g.dart" ] }
    build_to: source
    auto_apply: root_package
    defaults:
      generate_for:
        - lib/language/resources/*.key

  #TODO: 如何自定义参数？Option.config!
  #[builder_factories, import, build_extensions, target, auto_apply, required_inputs, runs_before, applies_builders, is_optional, build_to, defaults]
  languageResBuilder:
    import: "package:flutter_router_demo/language/builder.dart"
    builder_factories: [ "languageResBuilder" ]
    build_extensions: { ".json": [ ".g.dart" ] }
    build_to: source
    auto_apply: root_package
    applies_builders: [ "languageKeyBuilder" ]
    defaults:
      generate_for:
        - lib/language/resources/*.json

targets:
  $default:
    sources:
      # Need to replicate the default whitelist here or other build will break:
      - $package$
      - "benchmark/**"
      - "bin/**"
      - "example/**"
      - "lib/**"
      - "test/**"
      - "tool/**"
      - "web/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      # Project: custom src direction
#      - "assets/language/**"